"""FreeRADIUS config render / reload seam."""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from uuid import UUID

from jinja2 import Environment, FileSystemLoader, select_autoescape
from sqlalchemy import select, text
from sqlalchemy.orm import Session

from app.config import get_settings
from app.integrations.freeradius.sql_sync import sync_client_to_nas
from app.models.entities import RadiusClient

logger = logging.getLogger(__name__)
settings = get_settings()


def _env() -> Environment:
    template_dir = Path(settings.freeradius_templates_dir)
    template_dir.mkdir(parents=True, exist_ok=True)
    return Environment(
        loader=FileSystemLoader(str(template_dir)),
        autoescape=select_autoescape(enabled_extensions=()),
    )


def render_clients_config(clients: list[RadiusClient]) -> str:
    env = _env()
    try:
        template = env.get_template("clients.conf.j2")
        return template.render(clients=clients)
    except Exception:
        # Fallback if templates volume is missing during early bootstrap
        lines = ["# Generated by 802.1X Lab — do not edit by hand\n"]
        for client in clients:
            if not client.enabled:
                continue
            lines.append(
                f'client "{client.name}" {{\n'
                f"    ipaddr = {client.ip_address}\n"
                f'    secret = "{client.shared_secret}"\n'
                f"}}\n"
            )
        return "\n".join(lines)


def write_runtime_file(relative_name: str, content: str) -> Path:
    runtime = Path(settings.freeradius_config_dir)
    runtime.mkdir(parents=True, exist_ok=True)
    path = runtime / relative_name
    path.write_text(content, encoding="utf-8")
    return path


def request_reload() -> None:
    """Ask the FreeRADIUS container to reload clients/config.

    Primary mechanism: touch `reload.request` on the shared runtime volume.
    The FreeRADIUS entrypoint watcher runs `radmin hup` / SIGHUP.
    Optional: FREERADIUS_RELOAD_COMMAND for alternate environments.
    """
    runtime = Path(settings.freeradius_config_dir)
    runtime.mkdir(parents=True, exist_ok=True)
    flag = runtime / "reload.request"
    try:
        flag.write_text("reload\n", encoding="utf-8")
        logger.info("FreeRADIUS reload requested via %s", flag)
    except Exception:
        logger.exception("Failed to write FreeRADIUS reload flag")

    cmd = settings.freeradius_reload_command
    if cmd and cmd not in {'echo "reload-requested"', "echo reload-requested"}:
        logger.info("FreeRADIUS reload command: %s", cmd)
        try:
            subprocess.run(cmd, shell=True, check=False, capture_output=True, text=True)
        except Exception:
            logger.exception("FreeRADIUS reload command failed")


def sync_radius_clients(db: Session, lab_id: UUID) -> Path:
    clients = list(
        db.scalars(
            select(RadiusClient).where(RadiusClient.lab_id == lab_id).order_by(RadiusClient.name)
        ).all()
    )
    content = render_clients_config(clients)
    path = write_runtime_file("clients.dot1x.conf", content)

    # Rebuild FreeRADIUS `nas` rows for this lab (rlm_sql read_clients = yes).
    db.execute(text("DELETE FROM nas WHERE description = :d"), {"d": f"lab={lab_id}"})
    db.commit()
    for client in clients:
        sync_client_to_nas(db, client)

    request_reload()
    logger.info("Synced %s RADIUS clients to %s (+ nas)", len(clients), path)
    return path


def bootstrap_radius_runtime(db: Session) -> None:
    """Render clients for every lab and ensure NAS rows exist (startup)."""
    lab_ids = list(db.scalars(select(RadiusClient.lab_id).distinct()).all())
    if not lab_ids:
        write_runtime_file(
            "clients.dot1x.conf",
            "# Generated by 802.1X Lab — no clients yet\n",
        )
        return
    for lab_id in lab_ids:
        sync_radius_clients(db, lab_id)
