"""FreeRADIUS config render / reload seam (Phase 0 foundation)."""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from uuid import UUID

from jinja2 import Environment, FileSystemLoader, select_autoescape
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.config import get_settings
from app.models.entities import RadiusClient

logger = logging.getLogger(__name__)
settings = get_settings()


def _env() -> Environment:
    template_dir = Path(settings.freeradius_templates_dir)
    template_dir.mkdir(parents=True, exist_ok=True)
    return Environment(
        loader=FileSystemLoader(str(template_dir)),
        autoescape=select_autoescape(enabled_extensions=()),
    )


def render_clients_config(clients: list[RadiusClient]) -> str:
    env = _env()
    try:
        template = env.get_template("clients.conf.j2")
        return template.render(clients=clients)
    except Exception:
        # Fallback if templates volume is missing during early bootstrap
        lines = ["# Generated by 802.1X Lab — do not edit by hand\n"]
        for client in clients:
            if not client.enabled:
                continue
            lines.append(
                f'client "{client.name}" {{\n'
                f"    ipaddr = {client.ip_address}\n"
                f'    secret = "{client.shared_secret}"\n'
                f"}}\n"
            )
        return "\n".join(lines)


def write_runtime_file(relative_name: str, content: str) -> Path:
    runtime = Path(settings.freeradius_config_dir)
    runtime.mkdir(parents=True, exist_ok=True)
    path = runtime / relative_name
    path.write_text(content, encoding="utf-8")
    return path


def request_reload() -> None:
    """Signal FreeRADIUS to reload. Phase 0 logs the intent; Phase 1 wires radmin."""
    cmd = settings.freeradius_reload_command
    logger.info("FreeRADIUS reload requested: %s", cmd)
    try:
        subprocess.run(cmd, shell=True, check=False, capture_output=True, text=True)
    except Exception:
        logger.exception("FreeRADIUS reload command failed")


def sync_radius_clients(db: Session, lab_id: UUID) -> Path:
    clients = list(
        db.scalars(
            select(RadiusClient).where(RadiusClient.lab_id == lab_id).order_by(RadiusClient.name)
        ).all()
    )
    content = render_clients_config(clients)
    path = write_runtime_file("clients.dot1x.conf", content)
    request_reload()
    logger.info("Synced %s RADIUS clients to %s", len(clients), path)
    return path
