"""FreeRADIUS config render / reload seam."""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from uuid import UUID

from jinja2 import Environment, FileSystemLoader, select_autoescape
from sqlalchemy import select, text
from sqlalchemy.orm import Session

from app.config import get_settings
from app.integrations.freeradius.sql_sync import sync_client_to_nas
from app.models.entities import RadiusClient

logger = logging.getLogger(__name__)
settings = get_settings()


def _env() -> Environment:
    template_dir = Path(settings.freeradius_templates_dir)
    template_dir.mkdir(parents=True, exist_ok=True)
    return Environment(
        loader=FileSystemLoader(str(template_dir)),
        autoescape=select_autoescape(enabled_extensions=()),
    )


def client_address(client: RadiusClient) -> str:
    """The address FreeRADIUS matches this client on, in one comparable form."""
    return (client.ip_address or "").strip().lower()


def dedupe_clients_by_address(clients: list[RadiusClient]) -> list[RadiusClient]:
    """Keep one client per address.

    FreeRADIUS refuses to start when two `client` blocks share an address
    ("Failed to add duplicate client"), which would take the whole RADIUS server
    down rather than just the offending entry. Creating a duplicate is rejected
    at the API, but rows predating that rule must not be able to brick a restart.
    """
    seen: set[str] = set()
    unique: list[RadiusClient] = []
    for client in clients:
        address = client_address(client)
        if address in seen:
            logger.warning(
                "Skipping RADIUS client %r: %s is already claimed by another client",
                client.name,
                client.ip_address,
            )
            continue
        seen.add(address)
        unique.append(client)
    return unique


def render_clients_config(clients: list[RadiusClient]) -> str:
    enabled = dedupe_clients_by_address([c for c in clients if c.enabled])
    env = _env()
    try:
        template = env.get_template("clients.conf.j2")
        return template.render(clients=enabled)
    except Exception:
        # Fallback if templates volume is missing during early bootstrap
        lines = ["# Generated by 802.1X Lab — do not edit by hand\n"]
        for client in enabled:
            lines.append(
                f'client "{client.name}" {{\n'
                f"    ipaddr = {client.ip_address}\n"
                f'    secret = "{client.shared_secret}"\n'
                f"}}\n"
            )
        return "\n".join(lines)


def write_runtime_file(relative_name: str, content: str) -> Path:
    runtime = Path(settings.freeradius_config_dir)
    runtime.mkdir(parents=True, exist_ok=True)
    path = runtime / relative_name
    path.write_text(content, encoding="utf-8")
    return path


def request_reload() -> None:
    """Ask the FreeRADIUS container to HUP-reload modules/virtual servers.

    Primary mechanism: touch `reload.request` on the shared runtime volume.
    The FreeRADIUS entrypoint watcher runs `radmin hup` / SIGHUP.

    NOTE: FreeRADIUS 3.x does NOT re-read clients.conf (or its $INCLUDEs) on
    HUP — client changes require `request_restart()`. Keep this only for
    module-level config that HUP does honor.
    Optional: FREERADIUS_RELOAD_COMMAND for alternate environments.
    """
    runtime = Path(settings.freeradius_config_dir)
    runtime.mkdir(parents=True, exist_ok=True)
    flag = runtime / "reload.request"
    try:
        flag.write_text("reload\n", encoding="utf-8")
        logger.info("FreeRADIUS reload requested via %s", flag)
    except Exception:
        logger.exception("Failed to write FreeRADIUS reload flag")

    cmd = settings.freeradius_reload_command
    if cmd and cmd not in {'echo "reload-requested"', "echo reload-requested"}:
        logger.info("FreeRADIUS reload command: %s", cmd)
        try:
            subprocess.run(cmd, shell=True, check=False, capture_output=True, text=True)
        except Exception:
            logger.exception("FreeRADIUS reload command failed")


def request_restart() -> None:
    """Ask the FreeRADIUS container to fully restart (needed for ca_file trust updates)."""
    runtime = Path(settings.freeradius_config_dir)
    runtime.mkdir(parents=True, exist_ok=True)
    flag = runtime / "restart.request"
    try:
        flag.write_text("restart\n", encoding="utf-8")
        logger.info("FreeRADIUS restart requested via %s", flag)
    except Exception:
        logger.exception("Failed to write FreeRADIUS restart flag")


def sync_radius_clients(db: Session, lab_id: UUID) -> Path:
    # One FreeRADIUS instance serves every lab out of one clients file, so the
    # render is always the full set — writing just this lab's clients would
    # silently remove every other lab's NAS devices.
    clients = list(db.scalars(select(RadiusClient).order_by(RadiusClient.name)).all())
    lab_clients = [client for client in clients if client.lab_id == lab_id]
    content = render_clients_config(clients)
    clients_path = Path(settings.freeradius_config_dir) / "clients.dot1x.conf"
    changed = not clients_path.exists() or clients_path.read_text(encoding="utf-8") != content
    path = write_runtime_file("clients.dot1x.conf", content)

    # Rebuild FreeRADIUS `nas` rows for this lab (rlm_sql read_clients = yes).
    db.execute(text("DELETE FROM nas WHERE description = :d"), {"d": f"lab={lab_id}"})
    db.commit()
    for client in lab_clients:
        sync_client_to_nas(db, client)

    # FreeRADIUS 3.x only reads clients.conf at startup (HUP does not re-read
    # clients), so client changes need a controlled restart to take effect.
    if changed:
        request_restart()
    logger.info(
        "Synced %s RADIUS clients to %s (+ nas)%s",
        len(clients),
        path,
        " — restart requested" if changed else " — unchanged, no restart",
    )
    return path


def bootstrap_radius_runtime(db: Session) -> None:
    """Render clients for every lab and ensure NAS rows exist (startup)."""
    lab_ids = list(db.scalars(select(RadiusClient.lab_id).distinct()).all())
    if not lab_ids:
        write_runtime_file(
            "clients.dot1x.conf",
            "# Generated by 802.1X Lab — no clients yet\n",
        )
        return
    for lab_id in lab_ids:
        sync_radius_clients(db, lab_id)
