#!/usr/bin/env bash
# FreeRADIUS entrypoint for 802.1X Lab (Phase 1).
set -euo pipefail

FR_DIR="${FR_DIR:-/etc/freeradius/3.0}"
RUNTIME_DIR="${RUNTIME_DIR:-/etc/freeradius/dot1x-lab}"
LOG_DIR="${RUNTIME_DIR}/logs"
CLIENTS_FILE="${RUNTIME_DIR}/clients.dot1x.conf"
RELOAD_FLAG="${RUNTIME_DIR}/reload.request"
PID_FILE="${PID_FILE:-/var/run/freeradius/freeradius.pid}"

mkdir -p "${RUNTIME_DIR}" "${LOG_DIR}" "${RUNTIME_DIR}/certs" "${RUNTIME_DIR}/trusted" /var/run/freeradius
touch "${CLIENTS_FILE}"
chmod 644 "${CLIENTS_FILE}" || true
# World-readable lab auth log so the backend worker can tail it from the shared volume.
touch "${LOG_DIR}/auth.log"
chmod 666 "${LOG_DIR}/auth.log" || true
# Heartbeat file polled by the control-plane /api/health FreeRADIUS check.
echo "starting" >"${RUNTIME_DIR}/health.status"
chmod 666 "${RUNTIME_DIR}/health.status" || true

# Render SQL module connection from environment (Compose db service).
SQL_CONF="${FR_DIR}/mods-available/sql"
DB_HOST="${POSTGRES_HOST:-db}"
DB_PORT="${POSTGRES_PORT:-5432}"
DB_USER="${POSTGRES_USER:-dot1x}"
DB_PASSWORD="${POSTGRES_PASSWORD:-dot1x_lab_change_me}"
DB_NAME="${POSTGRES_DB:-dot1x_lab}"

cat >"${SQL_CONF}" <<EOF
# Generated by 802.1X Lab entrypoint — do not edit by hand
sql {
	dialect = "postgresql"
	driver = "rlm_sql_\${dialect}"

	postgresql {
		send_application_name = yes
	}

	# Single connection string for PostgreSQL (preferred over discrete server/login).
	radius_db = "host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable"

	acct_table1 = "radacct"
	acct_table2 = "radacct"
	postauth_table = "radpostauth"
	authcheck_table = "radcheck"
	groupcheck_table = "radgroupcheck"
	authreply_table = "radreply"
	groupreply_table = "radgroupreply"
	usergroup_table = "radusergroup"
	client_table = "nas"

	# Clients are loaded from rendered clients.dot1x.conf (not SQL) to avoid
	# duplicate IP conflicts with the nas mirror table.
	read_clients = no

	group_attribute = "SQL-Group"

	pool {
		start = 0
		min = 1
		max = 8
		spare = 1
		uses = 0
		retry_delay = 5
		lifetime = 0
		idle_timeout = 60
	}

	# Read database-specific queries (standard FreeRADIUS authorize/accounting).
	\$INCLUDE \${modconfdir}/\${.:name}/main/\${dialect}/queries.conf
}
EOF

ln -sfn ../mods-available/sql "${FR_DIR}/mods-enabled/sql"

# Wait for FreeRADIUS SQL schema (applied by backend Alembic migrate).
echo "Waiting for PostgreSQL FreeRADIUS tables at ${DB_HOST}:${DB_PORT}/${DB_NAME}..."
for i in $(seq 1 60); do
	if PGPASSWORD="${DB_PASSWORD}" psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" \
		-c "SELECT 1 FROM radcheck LIMIT 1" >/dev/null 2>&1; then
		echo "FreeRADIUS SQL schema is ready."
		break
	fi
	if [[ "${i}" -eq 60 ]]; then
		echo "WARNING: radcheck not ready after 60s; FreeRADIUS will retry SQL connections." >&2
	fi
	sleep 1
done

# Ensure EAP lab certs exist for PEAP/EAP-TLS server certificate presentation.
CERT_DIR="${FR_DIR}/certs"
echo "Ensuring FreeRADIUS EAP lab certificates..."
bash /usr/local/bin/generate-eap-certs.sh "${CERT_DIR}" || true
# freerad must be able to read EAP material after privilege drop.
chown -R freerad:freerad "${CERT_DIR}" 2>/dev/null || true
chmod 640 "${CERT_DIR}"/*.key 2>/dev/null || true
chmod 644 "${CERT_DIR}"/*.pem "${CERT_DIR}"/*.crt 2>/dev/null || true

# Export server CA onto the shared volume for backend eapol_test (PEAP/EAP-TLS).
if [[ -f "${CERT_DIR}/ca.pem" ]]; then
	cp "${CERT_DIR}/ca.pem" "${RUNTIME_DIR}/certs/ca.pem"
	chmod 644 "${RUNTIME_DIR}/certs/ca.pem" || true
	# Seed trust bundle so EAP-TLS ca_file path always exists; lab CAs are appended by the API.
	if [[ ! -f "${RUNTIME_DIR}/trusted/ca-bundle.pem" ]]; then
		cp "${CERT_DIR}/ca.pem" "${RUNTIME_DIR}/trusted/ca-bundle.pem"
		chmod 644 "${RUNTIME_DIR}/trusted/ca-bundle.pem" || true
	fi
fi

configure_eap_certs() {
	if [[ ! -f "${CERT_DIR}/server.pem" || ! -f "${CERT_DIR}/server.key" || ! -f "${CERT_DIR}/ca.pem" ]]; then
		return 0
	fi
	EAP_MOD="${FR_DIR}/mods-available/eap"
	# Bootstrap keys use passphrase "whatever"; our openssl fallback is unencrypted.
	if grep -q "ENCRYPTED" "${CERT_DIR}/server.key" 2>/dev/null; then
		KEY_PASS_LINE='		private_key_password = whatever'
	else
		KEY_PASS_LINE='		private_key_password ='
	fi
	# ca_file trusts client certs (EAP-TLS). Prefer the shared bundle (bootstrap + lab CAs).
	CA_FILE="${RUNTIME_DIR}/trusted/ca-bundle.pem"
	if [[ ! -f "${CA_FILE}" ]]; then
		CA_FILE="${CERT_DIR}/ca.pem"
	fi
	sed -i \
		-e "s|^[[:space:]]*private_key_password = .*|${KEY_PASS_LINE}|" \
		-e "s|^[[:space:]]*private_key_file = .*|		private_key_file = ${CERT_DIR}/server.key|" \
		-e "s|^[[:space:]]*certificate_file = .*|		certificate_file = ${CERT_DIR}/server.pem|" \
		-e "s|^[[:space:]]*ca_file = .*|		ca_file = ${CA_FILE}|" \
		"${EAP_MOD}"
	# Keep PEAP as default; EAP-TLS is selected by the client.
	sed -i 's/^[[:space:]]*default_eap_type = .*/	default_eap_type = peap/' "${EAP_MOD}" || true
}

configure_eap_certs

# Include control-plane rendered clients + lab Docker host client.
if ! grep -q 'dot1x-lab/clients.dot1x.conf' "${FR_DIR}/clients.conf"; then
	cat >>"${FR_DIR}/clients.conf" <<'EOF'

# 802.1X Lab — clients rendered by the control plane
$INCLUDE /etc/freeradius/dot1x-lab/clients.dot1x.conf
EOF
fi

# Published host ports appear as the Compose bridge gateway (often 172.18.0.1).
# Allow that path for local eapol_test / radtest from the Docker host.
if ! grep -q 'client lab-docker-host' "${FR_DIR}/clients.conf"; then
	cat >>"${FR_DIR}/clients.conf" <<'EOF'

# 802.1X Lab — Docker published-port source ranges (lab only)
client lab-docker-host {
	ipaddr = 172.16.0.0/12
	secret = testing123
}
client lab-docker-host-192 {
	ipaddr = 192.168.0.0/16
	secret = testing123
}
EOF
fi

# Enable control socket for radmin reload (needs mode=rw for hup).
CONTROL_SITE="${FR_DIR}/sites-available/control-socket"
if ! grep -q '^[[:space:]]*mode = rw' "${CONTROL_SITE}"; then
	# Uncomment / set mode = rw so radmin can issue hup.
	sed -i 's/^#[[:space:]]*mode = rw/	mode = rw/' "${CONTROL_SITE}"
	if ! grep -q '^[[:space:]]*mode = rw' "${CONTROL_SITE}"; then
		sed -i '/type = control/a\	mode = rw' "${CONTROL_SITE}"
	fi
fi
ln -sfn ../sites-available/control-socket "${FR_DIR}/sites-enabled/control-socket"

# Install linelog module for pinned DOT1X auth events.
cp /etc/freeradius/dot1x-lab-templates/linelog_dot1x \
	"${FR_DIR}/mods-available/linelog_dot1x"
ln -sfn ../mods-available/linelog_dot1x "${FR_DIR}/mods-enabled/linelog_dot1x"

# Ensure post-auth calls linelog_dot1x (idempotent).
ensure_linelog() {
	local site="$1"
	if ! grep -q 'linelog_dot1x' "${site}"; then
		# Soft-optional (-prefix) so a linelog glitch cannot convert Accept → Reject.
		sed -i \
			-e '/^post-auth {/a\	-linelog_dot1x' \
			-e '/Post-Auth-Type REJECT {/a\		-linelog_dot1x' \
			"${site}"
	fi
}
ensure_linelog "${FR_DIR}/sites-enabled/default"
ensure_linelog "${FR_DIR}/sites-enabled/inner-tunnel"

# Soft-fail SQL is already "-sql" in Debian sites; nothing else required for authorize.

CONTROL_SOCK="/var/run/freeradius/freeradius.sock"

request_reload() {
	# Prefer radmin over raw SIGHUP — more reliable with -f / job-control wrappers.
	if [[ -S "${CONTROL_SOCK}" ]]; then
		if radmin -f "${CONTROL_SOCK}" -e "hup"; then
			return 0
		fi
	fi
	if [[ -n "${FR_PID:-}" ]] && kill -0 "${FR_PID}" 2>/dev/null; then
		kill -HUP "${FR_PID}" 2>/dev/null || return 1
		sleep 1
		kill -0 "${FR_PID}" 2>/dev/null
		return $?
	fi
	return 1
}

reload_watcher() {
	while true; do
		# Refresh shared-volume heartbeat for control-plane health checks.
		echo "ok $(date -u +%Y-%m-%dT%H:%M:%SZ)" >"${RUNTIME_DIR}/health.status" 2>/dev/null || true

		# If the API published a new CA bundle, re-point EAP ca_file before reload.
		if [[ -f "${RUNTIME_DIR}/trusted/updated.flag" ]]; then
			rm -f "${RUNTIME_DIR}/trusted/updated.flag"
			configure_eap_certs
			# Ensure reload runs even if only trust material changed.
			touch "${RELOAD_FLAG}"
		fi

		if [[ -f "${RELOAD_FLAG}" ]]; then
			echo "Reload requested via ${RELOAD_FLAG}"
			rm -f "${RELOAD_FLAG}"
			if request_reload; then
				echo "FreeRADIUS reload completed"
			else
				echo "WARNING: FreeRADIUS reload failed" >&2
			fi
		fi
		sleep 1
	done
}

start_freeradius() {
	# Discard stale reload flags from previous runs so we do not HUP during boot.
	rm -f "${RELOAD_FLAG}"
	# Keep freeradius as a real child (do not disown) so `wait` works and EXIT
	# cleanup does not race with a detached process.
	freeradius -f -l stdout &
	FR_PID=$!
	echo "${FR_PID}" >"${PID_FILE}"

	# Wait for control socket (or process death) before enabling reload watcher.
	for _ in $(seq 1 30); do
		if [[ -S "${CONTROL_SOCK}" ]]; then
			echo "FreeRADIUS control socket is ready"
			return 0
		fi
		if ! kill -0 "${FR_PID}" 2>/dev/null; then
			echo "ERROR: FreeRADIUS exited during startup" >&2
			wait "${FR_PID}" || true
			return 1
		fi
		sleep 1
	done
	echo "WARNING: control socket not ready; reload watcher will use SIGHUP fallback" >&2
	return 0
}

start_freeradius

reload_watcher &
WATCHER_PID=$!

STOPPING=0
cleanup() {
	STOPPING=1
	kill "${WATCHER_PID}" 2>/dev/null || true
	if [[ -n "${FR_PID:-}" ]] && kill -0 "${FR_PID}" 2>/dev/null; then
		kill "${FR_PID}" 2>/dev/null || true
		wait "${FR_PID}" 2>/dev/null || true
	fi
}
trap cleanup EXIT INT TERM

# If FreeRADIUS exits on its own, end the container so Compose can restart it.
wait "${FR_PID}"
status=$?
if [[ "${STOPPING}" -eq 0 ]]; then
	echo "FreeRADIUS exited with status ${status}" >&2
fi
# Disable cleanup kill on normal wait completion (already dead).
trap - EXIT
kill "${WATCHER_PID}" 2>/dev/null || true
exit "${status}"
