#!/usr/bin/env bash
# FreeRADIUS entrypoint for 802.1X Lab (Phase 1).
set -euo pipefail

FR_DIR="${FR_DIR:-/etc/freeradius/3.0}"
RUNTIME_DIR="${RUNTIME_DIR:-/etc/freeradius/dot1x-lab}"
LOG_DIR="${RUNTIME_DIR}/logs"
CLIENTS_FILE="${RUNTIME_DIR}/clients.dot1x.conf"
RELOAD_FLAG="${RUNTIME_DIR}/reload.request"
PID_FILE="${PID_FILE:-/var/run/freeradius/freeradius.pid}"

mkdir -p "${RUNTIME_DIR}" "${LOG_DIR}" /var/run/freeradius
touch "${CLIENTS_FILE}"
chmod 644 "${CLIENTS_FILE}" || true
# World-readable lab auth log so the backend worker can tail it from the shared volume.
touch "${LOG_DIR}/auth.log"
chmod 666 "${LOG_DIR}/auth.log" || true

# Render SQL module connection from environment (Compose db service).
SQL_CONF="${FR_DIR}/mods-available/sql"
DB_HOST="${POSTGRES_HOST:-db}"
DB_PORT="${POSTGRES_PORT:-5432}"
DB_USER="${POSTGRES_USER:-dot1x}"
DB_PASSWORD="${POSTGRES_PASSWORD:-dot1x_lab_change_me}"
DB_NAME="${POSTGRES_DB:-dot1x_lab}"

cat >"${SQL_CONF}" <<EOF
# Generated by 802.1X Lab entrypoint — do not edit by hand
sql {
	dialect = "postgresql"
	driver = "rlm_sql_\${dialect}"

	postgresql {
		send_application_name = yes
	}

	# Single connection string for PostgreSQL (preferred over discrete server/login).
	radius_db = "host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable"

	acct_table1 = "radacct"
	acct_table2 = "radacct"
	postauth_table = "radpostauth"
	authcheck_table = "radcheck"
	groupcheck_table = "radgroupcheck"
	authreply_table = "radreply"
	groupreply_table = "radgroupreply"
	usergroup_table = "radusergroup"
	client_table = "nas"

	read_clients = yes

	group_attribute = "SQL-Group"

	pool {
		start = 0
		min = 1
		max = 8
		spare = 1
		uses = 0
		retry_delay = 5
		lifetime = 0
		idle_timeout = 60
	}

	# Read database-specific queries (standard FreeRADIUS authorize/accounting).
	\$INCLUDE \${modconfdir}/\${.:name}/main/\${dialect}/queries.conf
}
EOF

ln -sfn ../mods-available/sql "${FR_DIR}/mods-enabled/sql"

# Wait for FreeRADIUS SQL schema (applied by backend Alembic migrate).
echo "Waiting for PostgreSQL FreeRADIUS tables at ${DB_HOST}:${DB_PORT}/${DB_NAME}..."
for i in $(seq 1 60); do
	if PGPASSWORD="${DB_PASSWORD}" psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" \
		-c "SELECT 1 FROM radcheck LIMIT 1" >/dev/null 2>&1; then
		echo "FreeRADIUS SQL schema is ready."
		break
	fi
	if [[ "${i}" -eq 60 ]]; then
		echo "WARNING: radcheck not ready after 60s; FreeRADIUS will retry SQL connections." >&2
	fi
	sleep 1
done

# Ensure EAP lab certs exist (snakeoil works, but dedicated certs are clearer for PEAP).
CERT_DIR="${FR_DIR}/certs"
if [[ ! -f "${CERT_DIR}/server.pem" ]]; then
	echo "Generating FreeRADIUS EAP lab certificates..."
	if [[ -x "${CERT_DIR}/bootstrap" ]]; then
		(cd "${CERT_DIR}" && ./bootstrap) || true
	fi
fi
if [[ -f "${CERT_DIR}/server.pem" && -f "${CERT_DIR}/server.key" && -f "${CERT_DIR}/ca.pem" ]]; then
	# Point EAP TLS common config at generated lab certs when present.
	EAP_MOD="${FR_DIR}/mods-available/eap"
	sed -i \
		-e 's|^[[:space:]]*private_key_password = .*|		private_key_password = whatever|' \
		-e "s|^[[:space:]]*private_key_file = .*|		private_key_file = ${CERT_DIR}/server.key|" \
		-e "s|^[[:space:]]*certificate_file = .*|		certificate_file = ${CERT_DIR}/server.pem|" \
		-e "s|^[[:space:]]*ca_file = .*|		ca_file = ${CERT_DIR}/ca.pem|" \
		"${EAP_MOD}"
fi

# Include control-plane rendered clients.
if ! grep -q 'dot1x-lab/clients.dot1x.conf' "${FR_DIR}/clients.conf"; then
	cat >>"${FR_DIR}/clients.conf" <<'EOF'

# 802.1X Lab — clients rendered by the control plane
$INCLUDE /etc/freeradius/dot1x-lab/clients.dot1x.conf
EOF
fi

# Enable control socket for radmin reload.
ln -sfn ../sites-available/control-socket "${FR_DIR}/sites-enabled/control-socket"

# Install linelog module for pinned DOT1X auth events.
cp /etc/freeradius/dot1x-lab-templates/linelog_dot1x \
	"${FR_DIR}/mods-available/linelog_dot1x"
ln -sfn ../mods-available/linelog_dot1x "${FR_DIR}/mods-enabled/linelog_dot1x"

# Ensure post-auth calls linelog_dot1x (idempotent).
ensure_linelog() {
	local site="$1"
	if ! grep -q 'linelog_dot1x' "${site}"; then
		# Insert into post-auth and Post-Auth-Type REJECT blocks.
		sed -i \
			-e '/^post-auth {/a\	linelog_dot1x' \
			-e '/Post-Auth-Type REJECT {/a\		linelog_dot1x' \
			"${site}"
	fi
}
ensure_linelog "${FR_DIR}/sites-enabled/default"
ensure_linelog "${FR_DIR}/sites-enabled/inner-tunnel"

# Soft-fail SQL is already "-sql" in Debian sites; nothing else required for authorize.

request_reload() {
	if [[ -S /var/run/freeradius/freeradius.sock ]]; then
		radmin -f /var/run/freeradius/freeradius.sock -e hup && return 0
	fi
	if [[ -f "${PID_FILE}" ]]; then
		kill -HUP "$(cat "${PID_FILE}")" 2>/dev/null && return 0
	fi
	# Fallback: signal the freeradius child we started.
	if [[ -n "${FR_PID:-}" ]] && kill -0 "${FR_PID}" 2>/dev/null; then
		kill -HUP "${FR_PID}" 2>/dev/null && return 0
	fi
	return 1
}

reload_watcher() {
	while true; do
		if [[ -f "${RELOAD_FLAG}" ]]; then
			echo "Reload requested via ${RELOAD_FLAG}"
			if request_reload; then
				echo "FreeRADIUS reload completed"
			else
				echo "WARNING: FreeRADIUS reload failed" >&2
			fi
			rm -f "${RELOAD_FLAG}"
		fi
		sleep 1
	done
}

# Start FreeRADIUS in background so we can watch for reload flags.
# -f foreground relative to the daemonized child; we manage the process.
freeradius -f -l stdout &
FR_PID=$!
echo "${FR_PID}" >"${PID_FILE}"

reload_watcher &
WATCHER_PID=$!

cleanup() {
	kill "${WATCHER_PID}" 2>/dev/null || true
	kill "${FR_PID}" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

wait "${FR_PID}"
